Map<dynamic, dynamic> dogBreedList = {
  "Random": "",
  "affenpinscher": "affenpinscher",
  "african": "african",
  "airedale": "airedale",
  "akita": "akita",
  "appenzeller": "appenzeller",
  "shepherd australian": "australian-shepherd",
  "basenji": "basenji",
  "beagle": "beagle",
  "bluetick": "bluetick",
  "borzoi": "borzoi",
  "bouvier": "bouvier",
  "boxer": "boxer",
  "brabancon": "brabancon",
  "briard": "briard",
  "norwegian buhund": "buhund-norwegian",
  "boston bulldog": "bulldog-boston",
  "english bulldog": "bulldog-english",
  "french bulldog": "bulldog-french",
  "staffordshire bullterrier": "bullterrier-staffordshire",
  "australian cattledog": "cattledog-australian",
  "chihuahua": "chihuahua",
  "chow": "chow",
  "clumber": "clumber",
  "cockapoo": "cockapoo",
  "border collie": "collie-border",
  "coonhound": "coonhound",
  "cardigan corgi": "corgi-cardigan",
  "cotondetulear": "cotondetulear",
  "dachshund": "dachshund",
  "dalmatian": "dalmatian",
  "great dane": "dane-great",
  "scottish deerhound": "deerhound-scottish",
  "dhole": "dhole",
  "dingo": "dingo",
  "doberman": "doberman",
  "norwegian elkhound": "elkhound-norwegian",
  "entlebucher": "entlebucher",
  "eskimo": "eskimo",
  "lapphund finnish": "finnish-lapphund",
  "bichon frise": "frise-bichon",
  "germanshepherd": "germanshepherd",
  "italian greyhound": "greyhound-italian",
  "groenendael": "groenendael",
  "havanese": "havanese",
  "afghan hound": "hound-afghan",
  "basset hound": "hound-basset",
  "blood hound": "hound-blood",
  "english hound": "hound-english",
  "ibizan hound": "hound-ibizan",
  "plott hound": "hound-plott",
  "walker hound": "hound-walker",
  "husky": "husky",
  "keeshond": "keeshond",
  "kelpie": "kelpie",
  "komondor": "komondor",
  "kuvasz": "kuvasz",
  "labradoodle": "labradoodle",
  "labrador": "labrador",
  "leonberg": "leonberg",
  "lhasa": "lhasa",
  "malamute": "malamute",
  "malinois": "malinois",
  "maltese": "maltese",
  "bull mastiff": "mastiff-bull",
  "english mastiff": "mastiff-english",
  "tibetan mastiff": "mastiff-tibetan",
  "mexicanhairless": "mexicanhairless",
  "mix": "mix",
  "bernese mountain": "mountain-bernese",
  "swiss mountain": "mountain-swiss",
  "newfoundland": "newfoundland",
  "otterhound": "otterhound",
  "caucasian ovcharka": "ovcharka-caucasian",
  "papillon": "papillon",
  "pekinese": "pekinese",
  "pembroke": "pembroke",
  "miniature pinscher": "pinscher-miniature",
  "pitbull": "pitbull",
  "german pointer": "pointer-german",
  "germanlonghair pointer": "pointer-germanlonghair",
  "pomeranian": "pomeranian",
  "miniature poodle": "poodle-miniature",
  "standard poodle": "poodle-standard",
  "toy poodle": "poodle-toy",
  "pug": "pug",
  "puggle": "puggle",
  "pyrenees": "pyrenees",
  "redbone": "redbone",
  "chesapeake retriever": "retriever-chesapeake",
  "curly retriever": "retriever-curly",
  "flatcoated retriever": "retriever-flatcoated",
  "golden retriever": "retriever-golden",
  "rhodesian ridgeback": "ridgeback-rhodesian",
  "rottweiler": "rottweiler",
  "saluki": "saluki",
  "samoyed": "samoyed",
  "schipperke": "schipperke",
  "giant schnauzer": "schnauzer-giant",
  "miniature schnauzer": "schnauzer-miniature",
  "english setter": "setter-english",
  "gordon setter": "setter-gordon",
  "irish setter": "setter-irish",
  "english sheepdog": "sheepdog-english",
  "shetland sheepdog": "sheepdog-shetland",
  "shiba": "shiba",
  "shihtzu": "shihtzu",
  "blenheim spaniel": "spaniel-blenheim",
  "brittany spaniel": "spaniel-brittany",
  "cocker spaniel": "spaniel-cocker",
  "irish spaniel": "spaniel-irish",
  "japanese spaniel": "spaniel-japanese",
  "sussex spaniel": "spaniel-sussex",
  "welsh spaniel": "spaniel-welsh",
  "english springer": "springer-english",
  "stbernard": "stbernard",
  "american terrier": "terrier-american",
  "australian terrier": "terrier-australian",
  "bedlington terrier": "terrier-bedlington",
  "border terrier": "terrier-border",
  "cairn terrier": "terrier-cairn",
  "dandie terrier": "terrier-dandie",
  "fox terrier": "terrier-fox",
  "irish terrier": "terrier-irish",
  "kerryblue terrier": "terrier-kerryblue",
  "lakeland terrier": "terrier-lakeland",
  "norfolk terrier": "terrier-norfolk",
  "norwich terrier": "terrier-norwich",
  "patterdale terrier": "terrier-patterdale",
  "russell terrier": "terrier-russell",
  "scottish terrier": "terrier-scottish",
  "sealyham terrier": "terrier-sealyham",
  "silky terrier": "terrier-silky",
  "tibetan terrier": "terrier-tibetan",
  "toy terrier": "terrier-toy",
  "welsh terrier": "terrier-welsh",
  "westhighland terrier": "terrier-westhighland",
  "wheaten terrier": "terrier-wheaten",
  "yorkshire terrier": "terrier-yorkshire",
  "tervuren": "tervuren",
  "vizsla": "vizsla",
  "spanish waterdog": "waterdog-spanish",
  "weimaraner": "weimaraner",
  "whippet": "whippet",
  "irish wolfhound": "wolfhound-irish",
};
